(()=>{"use strict";
const products=window.ATHAR_PRODUCTS||[],grid=document.querySelector("#product-grid"),filters=document.querySelector("#filters"),search=document.querySelector("#product-search"),summary=document.querySelector("#results-summary"),empty=document.querySelector("#empty-state"),more=document.querySelector("#show-more"),drawer=document.querySelector("#cart-drawer"),backdrop=document.querySelector(".drawer-backdrop"),cartItems=document.querySelector("#cart-items"),cartEmpty=document.querySelector("#cart-empty"),cartFooter=document.querySelector("#cart-footer"),totalNode=document.querySelector("#cart-total"),toast=document.querySelector("#toast"),fmt=new Intl.NumberFormat("ar-SA"),PAGE=12,WA="966551902949";
let type="الكل",limit=PAGE,cart=readCart();
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function readCart(){try{return JSON.parse(localStorage.getItem("atharCart"))||{}}catch{return{}}}
function saveCart(){localStorage.setItem("atharCart",JSON.stringify(cart));renderCart()}
function matches(){const q=search.value.trim().toLocaleLowerCase("ar");return products.filter(p=>(type==="الكل"||p.type===type)&&(!q||`${p.name} ${p.type} ${p.category}`.toLocaleLowerCase("ar").includes(q)))}
function card(p){return `<article class="product-card"><div class="product-image"><img src="${esc(p.image)}" alt="${esc(p.name)}" width="480" height="480" loading="lazy" decoding="async"></div><div class="product-info"><div class="product-meta"><span>${esc(p.type)}</span><span>${esc(p.category)}</span></div><h3>${esc(p.name)}</h3><div class="product-buy"><span class="price">${fmt.format(p.price)} ر.س</span><button class="add-button" type="button" data-add="${p.id}">أضف للسلة</button></div></div></article>`}
function renderProducts(){const all=matches(),shown=all.slice(0,limit);grid.innerHTML=shown.map(card).join("");summary.textContent=`عرض ${fmt.format(shown.length)} من ${fmt.format(all.length)} منتج`;empty.hidden=all.length!==0;more.hidden=shown.length>=all.length}
function buildFilters(){const types=["الكل",...new Set(products.map(p=>p.type))];filters.innerHTML=types.map((t,i)=>`<button class="filter${i?"":" active"}" type="button" data-filter="${esc(t)}">${esc(t)}</button>`).join("")}
function announce(msg){toast.textContent=msg;toast.classList.add("show");clearTimeout(announce.timer);announce.timer=setTimeout(()=>toast.classList.remove("show"),2200)}
function add(id){cart[id]=(cart[id]||0)+1;saveCart();announce(`تمت إضافة ${products.find(p=>p.id===id).name} إلى السلة`)}
function rows(){return Object.entries(cart).map(([id,quantity])=>({product:products.find(p=>p.id===id),quantity})).filter(r=>r.product)}
function renderCart(){const data=rows(),count=data.reduce((s,r)=>s+r.quantity,0),total=data.reduce((s,r)=>s+r.product.price*r.quantity,0);document.querySelectorAll(".cart-count").forEach(n=>n.textContent=fmt.format(count));cartItems.innerHTML=data.map(({product:p,quantity:q})=>`<article class="cart-item"><img src="${esc(p.image)}" alt="" width="70" height="70"><div><h3>${esc(p.name)}</h3><p>${fmt.format(p.price)} ر.س</p><div class="qty"><button type="button" data-qty="-1" data-id="${p.id}" aria-label="تقليل الكمية">−</button><b>${fmt.format(q)}</b><button type="button" data-qty="1" data-id="${p.id}" aria-label="زيادة الكمية">+</button></div></div><button class="remove-item" type="button" data-remove="${p.id}" aria-label="حذف المنتج">×</button></article>`).join("");cartEmpty.hidden=data.length>0;cartFooter.hidden=data.length===0;totalNode.textContent=`${fmt.format(total)} ر.س`}
function openCart(){drawer.classList.add("open");drawer.setAttribute("aria-hidden","false");backdrop.hidden=false;document.body.classList.add("drawer-open")}
function closeCart(){drawer.classList.remove("open");drawer.setAttribute("aria-hidden","true");backdrop.hidden=true;document.body.classList.remove("drawer-open")}
function qty(id,delta){if(!cart[id])return;cart[id]+=delta;if(cart[id]<=0)delete cart[id];saveCart()}
function send(){const data=rows();if(!data.length)return;const total=data.reduce((s,r)=>s+r.product.price*r.quantity,0),lines=data.map((r,i)=>`${i+1}) ${r.product.name} — الكمية: ${r.quantity} — ${r.product.price*r.quantity} ر.س`),message=["مرحبًا أثر ولمسة، أرغب في طلب المنتجات التالية:","",...lines,"",`الإجمالي المبدئي: ${total} ر.س`,"","أرغب في تأكيد المقاسات والألوان والتوصيل."].join("\n");window.open(`https://wa.me/${WA}?text=${encodeURIComponent(message)}`,"_blank","noopener")}
filters.addEventListener("click",e=>{const b=e.target.closest("[data-filter]");if(!b)return;type=b.dataset.filter;limit=PAGE;filters.querySelectorAll(".filter").forEach(n=>n.classList.toggle("active",n===b));renderProducts()});
search.addEventListener("input",()=>{limit=PAGE;renderProducts()});more.addEventListener("click",()=>{limit+=PAGE;renderProducts()});grid.addEventListener("click",e=>{const b=e.target.closest("[data-add]");if(b)add(b.dataset.add)});
cartItems.addEventListener("click",e=>{const q=e.target.closest("[data-qty]"),r=e.target.closest("[data-remove]");if(q)qty(q.dataset.id,Number(q.dataset.qty));if(r){delete cart[r.dataset.remove];saveCart()}});
document.querySelectorAll("[data-open-cart]").forEach(n=>n.addEventListener("click",openCart));document.querySelectorAll("[data-close-cart]").forEach(n=>n.addEventListener("click",closeCart));document.querySelector("#send-order").addEventListener("click",send);document.querySelector("#clear-cart").addEventListener("click",()=>{cart={};saveCart()});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeCart()});
document.querySelector(".menu-toggle").addEventListener("click",e=>{const menu=document.querySelector("#nav-links"),open=menu.classList.toggle("open");e.currentTarget.setAttribute("aria-expanded",String(open))});document.querySelectorAll("#nav-links a").forEach(a=>a.addEventListener("click",()=>document.querySelector("#nav-links").classList.remove("open")));
document.querySelector("#year").textContent=new Date().getFullYear().toLocaleString("ar-SA",{useGrouping:false});buildFilters();renderProducts();renderCart();
})();
