window.ATHAR_PRODUCTS=[
{id:"s01",type:"تيشيرتات",category:"سعودي",name:"روح السعودية",price:89,image:"shirts/shirt-1.jpg"},
{id:"s02",type:"تيشيرتات",category:"سعودي",name:"النخلة والسيف",price:89,image:"shirts/shirt-2.jpg"},
{id:"s03",type:"تيشيرتات",category:"عبارات",name:"قوة بداخلك",price:89,image:"shirts/shirt-3.jpg"},
{id:"s04",type:"تيشيرتات",category:"سعودي",name:"مشاهد سعودية",price:89,image:"shirts/shirt-4.jpg"},
{id:"s05",type:"تيشيرتات",category:"سعودي",name:"ذاكرة المكان",price:89,image:"shirts/shirt-5.jpg"},
{id:"s06",type:"تيشيرتات",category:"رسومات",name:"ملك الغابة",price:89,image:"shirts/shirt-6.jpg"},
{id:"s07",type:"تيشيرتات",category:"طبيعة",name:"القمر والشجرة",price:89,image:"shirts/shirt-7.jpg"},
{id:"s08",type:"تيشيرتات",category:"فن",name:"ملامح",price:79,image:"shirts/shirt-8.jpg"},
{id:"s09",type:"تيشيرتات",category:"فضاء",name:"رائد الفضاء",price:89,image:"shirts/shirt-9.jpg"},
{id:"s10",type:"تيشيرتات",category:"عبارات",name:"الأشياء الجميلة تحتاج وقتًا",price:89,image:"shirts/shirt-10.jpg"},
{id:"s11",type:"تيشيرتات",category:"عبارات",name:"الانضباط يصنع الحرية",price:89,image:"shirts/shirt-11.jpg"},
{id:"s12",type:"تيشيرتات",category:"أنمي",name:"استمر بالمضي",price:89,image:"shirts/shirt-12.jpg"},
{id:"s13",type:"تيشيرتات",category:"لايف ستايل",name:"قهوة",price:79,image:"shirts/shirt-13.jpg"},
{id:"s14",type:"تيشيرتات",category:"رسومات",name:"قط بنظارة",price:89,image:"shirts/shirt-14.jpg"},
{id:"s15",type:"تيشيرتات",category:"طبيعة",name:"غصن نباتي",price:79,image:"shirts/shirt-15.jpg"},
{id:"s16",type:"تيشيرتات",category:"طبيعة",name:"ضوء القمر",price:89,image:"shirts/shirt-16.jpg"},
{id:"s17",type:"تيشيرتات",category:"طبيعة",name:"قمم",price:89,image:"shirts/shirt-17.jpg"},
{id:"s18",type:"تيشيرتات",category:"ألعاب",name:"جولة أخيرة",price:89,image:"shirts/shirt-18.jpg"},
{id:"s19",type:"تيشيرتات",category:"فضاء",name:"نحو القمر",price:89,image:"shirts/shirt-19.jpg"},
{id:"s20",type:"تيشيرتات",category:"طبيعة",name:"غصن الربيع",price:79,image:"shirts/shirt-20.jpg"},
{id:"s21",type:"تيشيرتات",category:"عبارات",name:"تركيز",price:89,image:"shirts/shirt-21.jpg"},
{id:"s22",type:"تيشيرتات",category:"طبيعة",name:"أفق هادئ",price:89,image:"shirts/shirt-22.jpg"},
{id:"s23",type:"تيشيرتات",category:"عبارات",name:"أفضل من الأمس",price:89,image:"shirts/shirt-23.jpg"},
{id:"s24",type:"تيشيرتات",category:"رسومات",name:"الحصان العربي",price:89,image:"shirts/shirt-24.jpg"},
{id:"m01",type:"أكواب",category:"سعودي",name:"كوب روح السعودية",price:59,image:"mugs/mug-1.jpg"},
{id:"m02",type:"أكواب",category:"سعودي",name:"كوب النخلة والسيف",price:59,image:"mugs/mug-2.jpg"},
{id:"m03",type:"أكواب",category:"سعودي",name:"كوب ذاكرة المكان",price:59,image:"mugs/mug-3.jpg"},
{id:"m04",type:"أكواب",category:"رسومات",name:"كوب ملك الغابة",price:59,image:"mugs/mug-4.jpg"},
{id:"m05",type:"أكواب",category:"عبارات",name:"كوب قوة بداخلك",price:59,image:"mugs/mug-5.jpg"},
{id:"m06",type:"أكواب",category:"طبيعة",name:"كوب القمر والشجرة",price:59,image:"mugs/mug-6.jpg"},
{id:"m07",type:"أكواب",category:"فن",name:"كوب ملامح",price:59,image:"mugs/mug-7.jpg"},
{id:"m08",type:"أكواب",category:"فضاء",name:"كوب رائد الفضاء",price:59,image:"mugs/mug-8.jpg"},
{id:"m09",type:"أكواب",category:"عبارات",name:"كوب الأشياء الجميلة",price:59,image:"mugs/mug-9.jpg"},
{id:"m10",type:"أكواب",category:"عبارات",name:"كوب الانضباط",price:59,image:"mugs/mug-10.jpg"},
{id:"m11",type:"أكواب",category:"أنمي",name:"كوب استمر بالمضي",price:59,image:"mugs/mug-11.jpg"},
{id:"m12",type:"أكواب",category:"لايف ستايل",name:"كوب قهوة",price:59,image:"mugs/mug-12.jpg"},
{id:"m13",type:"أكواب",category:"رسومات",name:"كوب قط بنظارة",price:59,image:"mugs/mug-13.jpg"},
{id:"m14",type:"أكواب",category:"طبيعة",name:"كوب غصن نباتي",price:59,image:"mugs/mug-14.jpg"},
{id:"m15",type:"أكواب",category:"طبيعة",name:"كوب القمم",price:59,image:"mugs/mug-15.jpg"},
{id:"m16",type:"أكواب",category:"فضاء",name:"كوب نحو القمر",price:59,image:"mugs/mug-16.jpg"},
{id:"c01",type:"كفرات",category:"سعودي",name:"كفر روح السعودية",price:69,image:"other-products/case-1.jpg"},
{id:"c02",type:"كفرات",category:"سعودي",name:"كفر النخلة والسيف",price:69,image:"other-products/case-2.jpg"},
{id:"c03",type:"كفرات",category:"عبارات",name:"كفر الانضباط",price:69,image:"other-products/case-3.jpg"},
{id:"c04",type:"كفرات",category:"فضاء",name:"كفر الفضاء",price:69,image:"other-products/case-4.jpg"},
{id:"k01",type:"استيكرات",category:"سعودي",name:"باقة استيكرات سعودية",price:29,image:"other-products/sticker-1.jpg"},
{id:"k02",type:"استيكرات",category:"سعودي",name:"باقة استيكرات النخلة",price:29,image:"other-products/sticker-2.jpg"},
{id:"k03",type:"استيكرات",category:"عبارات",name:"باقة استيكرات عبارات",price:29,image:"other-products/sticker-3.jpg"},
{id:"k04",type:"استيكرات",category:"فضاء",name:"باقة استيكرات فضاء",price:29,image:"other-products/sticker-4.jpg"},
{id:"d01",type:"طباعة 3D",category:"سعودي",name:"إطار 3D سعودي",price:79,image:"other-products/3d-1.jpg"},
{id:"d02",type:"طباعة 3D",category:"سعودي",name:"إطار 3D بالنخلة",price:79,image:"other-products/3d-2.jpg"},
{id:"d03",type:"طباعة 3D",category:"عبارات",name:"ستاند 3D بالانضباط",price:89,image:"other-products/3d-3.jpg"},
{id:"d04",type:"طباعة 3D",category:"فضاء",name:"إطار 3D للفضاء",price:99,image:"other-products/3d-4.jpg"}
];
